name: workflow from part 4 to part9
on : 
   workflow_dispatch:
     branches: main
jobs: 
  systeminfo:
    name: execute the system related information
    runs-on: ubuntu-latest
    steps:
     - name: identifying the name
       run: uname -r
     - name: identifying the hostname
       run: hostname
     - name: identifying the os
       run: cat /etc/os-release
     - name: print few env variable
       run: echo "My name is $RUNNER_NAME"
     - name: set custom variable
       run: echo "WINNER_NAME=Ganesh" >> $GITHUB_ENV
     - name: creating a file
       run: echo -e "My name is $RUNNER_NAME\nWinner is $WINNER_NAME" > prizes.txt
     - name: print specific text from the above file
       run: cat prizes.txt | grep "name"
     - name: conversion from small to big
       run: cat prizes.txt | tr 'a-z' 'A-Z'
     - name: check the word count
       run: cat prizes.txt | wc -w
     - name: List files
       run: ls -ltr
     - name: Checkout repository
       uses: actions/checkout@v4
     - name: List all files
       run: ls -ltr
     - name: reading readme.md file
       run: cat README.md
     - name: running multiple commands
       run: |
        uname -r
        hostname
        cat /etc/os-release
     - name: execute the shell script
       run: sh fruits.sh
