name: part4 workflow1
on : 
   push:
     branches: main
jobs: 
  systeminfo:
    name: execute the system related information
    runs-on: ubuntu-latest
    steps:
     - name: identifying the name
       run: uname -r
     - name: identifying the hostname
       run: hostname
     - name: identifying the os
       run: cat /etc/os-release
     - name: print few env variable
       run: echo "My name is $RUNNER_NAME"
     - name: custom variables
       run: |
         WINNER_NAME="Ganesh"
         echo "Winner is $WINNER_NAME"
     - name: creating an file
       run: echo "My name is $RUNNER_NAME Winner is $WINNER_NAME" > prizes.txt
     - name: print specific text from the above file
       run: cat prizes.txt | grep "name"
     - name: conversion from small to big
       run: cat prizes.txt | tr 'a-z' 'A-Z'
     - name: check the word count
       run: cat prizes.txt | wc -w
     - name: List files
       run: ls -ltr
