name: my first githubactions workflow
on: push
jobs:
  basic-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Update the packages
        run: sudo apt-get update
      - name: Install git
        run: sudo apt-get install -y git
