name : my first githubactions workflow
  on : push
  jobs:
    basic-demo:
      runs-on : ubuntu-server
      steps:
       - name: update the packages
         run : apt-get update 
       - name: install git 
         run : apt-get install git