name: All linux commands

on: push

jobs:
   linux-job:
    runs-on: ubuntu-latest
    steps:
      - name: display the name
        run: uname
        
      - name: display the current directory
        run: pwd
        
      - name: list all the files and directories
        run : ls -lrtha
